# Generated by Django 2.0.7 on 2018-07-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, 'Not Done'), (1, 'Done')], default=1)),
                ('text', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
